# Generated by Django 3.2.9 on 2022-01-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20220111_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'ordering': ('id',)},
        ),
    ]
