# Generated by Django 3.2.9 on 2022-02-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20220113_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
