# Generated by Django 3.2.9 on 2022-02-11 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_delete_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(
                related_name='_woof_user_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
