# Generated by Django 3.2.9 on 2022-05-17 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='woof',
            name='likes',
            field=models.ManyToManyField(
                blank=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
